version: '3'

services:
  db:
    image: mdillon/postgis:11
    environment:
        POSTGRES_DB: farmhelden
        POSTGRES_USER: farmheldenuser
        POSTGRES_PASSWORD: password
    networks:
      internal:
        aliases:
          - farmhelden.db

  api:
    build: .
    entrypoint: ["custom-entrypoint.sh", "development"]
    volumes:
      - ./farmhelden:/farmhelden
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - farmhelden.api

networks:
  internal:
